default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: data/materia_medica_dev.sqlite3

test:
  <<: *default
  database: data/materia_medica_test.sqlite3

production:
  <<: *default
  database: data/materia_medica.sqlite3
